import { poppins } from '@/resources/config/fonts';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Music App Song</title>
        <meta
          name="description"
          content="App musics dashboard for administrate musics."
        />
      </head>
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
